version: 2.1
orbs:
  # this contains recpes (install node, aws, other)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # get some jobs in the workflows
  
  
jobs:
  build:
    docker:
      # base image
      - image: "cimg/node:14.15"
    steps:
      # install node and make checks on it
      
      - node/install:
          node-version: '14.15'         
      - checkout
      # Use package.json to install depndences in frontend
      
      
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # TODO: Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: |
           echo "TODO: Install dependencies in the the backend API "
           npm run api:install

      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "TODO: Build the frontend app"
            npm run frontend:build
      # TODO: Build the backend API      
      - run:
          name: API Build
          command: |
            echo "TODO: Build the backend API"
            npm run api:build
  # this step will run after manual

  test:
    docker:
      - image: "cimg/base:stable"
      # setup needed for test the app
    steps:
      - run:
          name: Test FrontEnd
          # TODO: Install, build, deploy in both apps
          command: |
            echo "# TODO: Testing FrontEnd"

  deploy:
    docker:
      - image: "cimg/base:stable"
      # setup for aws, node, EB
      
    steps:
      - node/install:
          node-version: '14.15' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Envs
          # TODO: Install, build, deploy in both apps
          command: |
            echo "# TODO: Install, build, deploy in both apps"
            eb init test-api-dev --platform node.js --region us-east-1
            echo "# Deploy"
            npm run deploy
            echo "# use Elastic Beanstalk"
            eb use test-api-dev
            echo "# Elastic Beanstalk Env"
            eb setenv POSTGRES_HOST=$POSTGRES_HOST DB_PORT=$DB_PORT POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_DB=$POSTGRES_DB JWT_SECRET=$JWT_SECRET PORT=$PORT

workflows:
  udagram:
    jobs:
      - test
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
      - deploy:
          requires:
            - hold

