version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'         
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install      
      - run:
          name: Install API Dependencies
          command: |
           npm run api:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run api:build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Test FrontEnd
          command: |
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Envs
          command: |
            eb init test-api-dev --platform node.js --region us-east-1
            echo "# Deploy"
            npm run deploy
            echo "# use EB"
            eb use test-api-dev
            echo "# EB setenvs"
            eb setenv POSTGRES_HOST=$POSTGRES_HOST DB_PORT=$DB_PORT POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_DB=$POSTGRES_DB JWT_SECRET=$JWT_SECRET PORT=$PORT

workflows:
  udagram:
    jobs:
      - test
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
      - deploy:
          requires:
            - hold

